language: go

services:
- postgresql

addons:
  postgresql: "9.3"

go:
  - 1.3
  - 1.4
  - 1.5

install:
  - go get gopkg.in/bufio.v1
  - go get gopkg.in/bsm/ratelimit.v1
  - go get github.com/golang/glog
  - go get github.com/go-sql-driver/mysql
  - go get github.com/lib/pq
  - go get gopkg.in/check.v1
  - go get github.com/onsi/ginkgo
  - go get github.com/onsi/gomega
  - mkdir -p $HOME/gopath/src/gopkg.in
  - ln -s `pwd` $HOME/gopath/src/gopkg.in/pg.v3

before_script:
  - psql -c 'CREATE DATABASE test' -U postgres
