language: go

services:
- postgresql

go:
  - 1.1
  - 1.2
  - tip

install:
  - go get github.com/vmihailenco/bufio
  - go get github.com/golang/glog
  - go get github.com/go-sql-driver/mysql
  - go get github.com/lib/pq
  - go get launchpad.net/gocheck
  - mkdir -p $HOME/gopath/src/gopkg.in
  - ln -s `pwd` $HOME/gopath/src/gopkg.in/pg.v2.1

before_script:
  - psql -c 'CREATE DATABASE test;' -U postgres
